### ISSUE TITLE
Enumerator method problem in ruby 1.9.2

### ISSUE THREAD

**Issue by wemerson** [anujluthra/barcode-generator#6]
Love how easy this make barcode creation but I have a problem displaying the barcode. I had some trouble getting everything installed but now I can generate an eps file just fine but it fails to create the png file and display the barcode in the view. I get this error:

ActionView::Template::Error (undefined method `join' for #<Enumerator: []:collect>):
    9:   <%= @label.description %>
    10: </p>
    11: 
    12: <p><%= barcode @label.code %></p>
    13: 
    14: <p>
    15:   <%= link_to "Edit", edit_label_path(@label) %> |
  app/views/labels/show.html.erb:12:in`_app_views_labels_show_html_erb___1939771989001282335_2169264860_1747278781368551234'

When I run the tests, it points back to barcode_generator/lib/imagemagickwrapper.rb

system("convert #{options.collect.join(' ')} #{src} #{out}")

The error says Enumerable doesn't have a method 'join'.

When I run convert from the command line with no options, it creates the png file. When I remove options from the imagemagickwrapper.rb line, the barcode displays fine in the view.

I'm not well-versed in ruby innards so I'm not attempting a fix, just reporting. 
I'm using ruby 1.9.2
rails 3.0.9
imagemagick 6.7.1-1
gbarcode for ruby 1.9

Thanks for any help,
Will Emerson

**Comment by taasaa** [comment]
Just replace this line:

```
system("convert #{options.collect.join(' ')} #{src} #{out}")
```

with this one:

```
system("convert #{options.join(' ')} #{src} #{out}")
```

Worked for me.

**Comment by wemerson** [comment]
Wow! That was easy. Thanks!
